title: LaTeX by PacMat99
description: Guida introduttiva a LaTeX
theme: just-the-docs

url: https://latex.pacsbrothers.com

logo: "./images/logo.png"
favicon_ico: "favicon.ico"

aux_links:
  "Instagram":
    - "https://www.instagram.com/mattiapacchin"
  "GitHub":
    - "https://github.com/PacMat99/nodered_guide"

aux_links_new_tab: true

color_scheme: dark